temporal_steps: 100
spatial_steps: 200

temporal_classifier_layer: 1
temporal_encoder_layer: 3
temporal_mix_components: 8
temporal_hidden_dims: 32
temporal_kernel_size: 5
temporal_time_segments: 24
spatial_hidden_dims: 256

num_condition_types: 6

# Constraint Projection 参数
use_constraint_projection: True
projection_tau: 0
projection_delta_tal: 0.000001
projection_lambda: 1.0          # λinit
projection_mu: 1.0              # μinit
projection_mu_max: 1000.0       # μmax
projection_outer_iters: 20    # outer_itermax
projection_inner_iters: 50     # inner_itermax
projection_mu_alpha: 2.0        # α，放大 μ
projection_eta: 0.8             # η
projection_alm_iters: 10
projection_frequency: 2
use_gumbel_softmax: true
gumbel_temperature: 0.1
projection_last_k_steps: 50
projection_existence_weight: 5.0